language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi

script:
 # Test
 - python setup.py test

 # Static analysis
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi
